#pragma once
#include <map>
#include <iostream>
#include <Windows.h>

std::map<std::uint8_t, std::string> Keycodes{
    {VK_MBUTTON, "MBUTTON"},
    {VK_XBUTTON1, "XBUTTON1"},
    {VK_XBUTTON2, "XBUTTON2"},

    {VK_SHIFT, "SHIFT"},
    {VK_LSHIFT, "LSHIFT"},
    {VK_RSHIFT, "RSHIFT"},

    {VK_CONTROL, "CTRL"},
    {VK_LCONTROL, "LCTRL"},
    {VK_RCONTROL, "RCTRL"},

    {VK_MENU, "ALT"},
    {VK_LMENU, "LALT"},
    {VK_RMENU, "RALT"},

    {VK_TAB, "TAB"},
    {VK_BACK, "BACKSPACE"},
    {VK_RETURN, "ENTER"},
    {VK_PAUSE, "PAUSE"},
    {VK_CAPITAL, "CAPS"},
    {VK_ESCAPE, "ESCAPE"},
    {VK_SPACE, "SPACE"},
    {VK_PRIOR, "PAGEUP"},
    {VK_NEXT, "PAGEDOWN"},
    {VK_END, "END"},
    {VK_HOME, "HOME"},
    {VK_SELECT, "SELECT"},
    {VK_PRINT, "PRINTSCREEN"},
    {VK_NUMLOCK, "NUM_LOCK"},
    {VK_SCROLL, "SCROLL_LOCK"},

    {0x30, "0"},
    {0x31, "1"},
    {0x32, "2"},
    {0x33, "3"},
    {0x34, "4"},
    {0x35, "5"},
    {0x36, "6"},
    {0x37, "7"},
    {0x38, "8"},
    {0x39, "9"},

    {VK_NUMPAD0, "NUMPAD_0"},
    {VK_NUMPAD1, "NUMPAD_1"},
    {VK_NUMPAD2, "NUMPAD_2"},
    {VK_NUMPAD3, "NUMPAD_3"},
    {VK_NUMPAD4, "NUMPAD_4"},
    {VK_NUMPAD5, "NUMPAD_5"},
    {VK_NUMPAD6, "NUMPAD_6"},
    {VK_NUMPAD7, "NUMPAD_7"},
    {VK_NUMPAD8, "NUMPAD_8"},
    {VK_NUMPAD9, "NUMPAD_9"},

    {VK_F1, "F1"},
    {VK_F2, "F2"},
    {VK_F3, "F3"},
    {VK_F4, "F4"},
    {VK_F5, "F5"},
    {VK_F6, "F6"},
    {VK_F7, "F7"},
    {VK_F8, "F8"},
    {VK_F9, "F9"},
    {VK_F10, "F10"},
    {VK_F11, "F11"},
    {VK_F12, "F12"},

    {0x41, "A"},
    {0x42, "B"},
    {0x43, "C"},
    {0x44, "D"},
    {0x45, "E"},
    {0x46, "F"},
    {0x47, "G"},
    {0x48, "H"},
    {0x49, "I"},
    {0x4A, "J"},
    {0x4B, "K"},
    {0x4C, "L"},
    {0x4D, "M"},
    {0x4E, "N"},
    {0x4F, "O"},
    {0x50, "P"},
    {0x51, "Q"},
    {0x52, "R"},
    {0x53, "S"},
    {0x54, "T"},
    {0x55, "U"},
    {0x56, "V"},
    {0x57, "W"},
    {0x58, "X"},
    {0x59, "Y"},
    {0x5A, "Z"},

    {VK_LEFT, "LEFT"},
    {VK_UP, "UP"},
    {VK_RIGHT, "RIGHT"},
    {VK_DOWN, "DOWN"},
};
